### ISSUE TITLE
Style rule issue

### ISSUE THREAD

**Issue by kwickramasekara** [lucleray/hyper-active-tab#1]
https://github.com/lucleray/hyper-active-tab/blob/bfd9d0973cf4fef62e13b7ea0d17a712e3146685/index.js#L24

Seems like a stray rule? `color` is already defined on L22

**Comment by lucleray** [comment]
Thanks for the catch 👍

I fixed it (343862ee8566a4971a479b97e0a6770338e715dc) and published a new version
